### ISSUE TITLE
Upload failure on slow repository creation

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#215]
```
2017-01-12T15:55:05.762466+00:00 app[web.1]: Started GET "/datasets/new" for 85.115.54.201 at 2017-01-12 15:55:05 +0000
2017-01-12T15:55:05.767016+00:00 app[web.1]: Processing by DatasetsController#new as HTML
2017-01-12T15:55:07.904663+00:00 app[web.1]:   Rendered dataset_files/_form.html.erb (7.9ms)
2017-01-12T15:55:07.906713+00:00 app[web.1]:   Rendered datasets/new.html.erb within layouts/fsa-application (1036.9ms)
2017-01-12T15:55:07.907705+00:00 app[web.1]: Completed 200 OK in 2141ms (Views: 1034.2ms | ActiveRecord: 19.1ms)
2017-01-12T15:55:07.906642+00:00 app[web.1]:   Rendered datasets/_form.html.erb (1035.4ms)
2017-01-12T15:55:07.899650+00:00 heroku[router]: at=info method=GET path="/datasets/new" host=fsa-octopub.herokuapp.com request_id=9634a393-2631-4f1a-b76a-4a1ff3383cd7 fwd="85.115.54.201" dyno=web.1 connect=0ms service=2148ms status=200 bytes=14211
2017-01-12T15:56:07.282700+00:00 app[web.1]: Started POST "/datasets" for 85.115.54.201 at 2017-01-12 15:56:07 +0000
2017-01-12T15:56:07.285076+00:00 app[web.1]: Processing by DatasetsController#create as */*
2017-01-12T15:56:07.285984+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<redacted>", "dataset"=>{"name"=>"Approved Food Establishments", "owner"=>"fsadata", "description"=>"A full list of establishments approved to handle, prepare or produce products of animal origin for which requirements are laid down in Regulation (EC) No 853/2004.", "publisher_name"=>"Food Standards Agency", "publisher_url"=>"https://www.food.gov.uk", "license"=>"OGL-UK-3.0", "frequency"=>"Monthly", "schema"=>"https://fsa-octopub.s3-eu-west-1.amazonaws.com/uploads/<redacted>/ApprovedFoodEstablishments.json"}, "files"=>[{"title"=>"Approved Food Establishments", "description"=>"A full list of establishments approved to handle, prepare or produce products of animal origin for which requirements are laid down in Regulation (EC) No 853/2004.", "file"=>"https://fsa-octopub.s3-eu-west-1.amazonaws.com/uploads/<redacted>/ApprovedFoodEstablishments.csv"}], "async"=>"true", "channel_id"=>"<redacted>"}
2017-01-12T15:56:07.816305+00:00 app[worker.1]: 4 TID-ovdtne87g CreateDataset JID-b17ae9ac5570d685bcbfadaa INFO: start
2017-01-12T15:56:07.825616+00:00 app[web.1]: Completed 202 Accepted in 539ms (ActiveRecord: 1.0ms)
2017-01-12T15:56:07.816951+00:00 heroku[router]: at=info method=POST path="/datasets" host=fsa-octopub.herokuapp.com request_id=2b2c1162-d95a-417a-b350-3ce972dc543a fwd="85.115.54.201" dyno=web.1 connect=1ms service=560ms status=202 bytes=667
2017-01-12T15:56:15.621692+00:00 app[web.1]: Started GET "/datasets/created" for 85.115.54.201 at 2017-01-12 15:56:15 +0000
2017-01-12T15:56:15.623936+00:00 app[web.1]: Processing by DatasetsController#created as HTML
2017-01-12T15:56:15.627619+00:00 app[web.1]:   Rendered datasets/created.html.erb within layouts/fsa-application (0.4ms)
2017-01-12T15:56:15.628987+00:00 app[web.1]: Completed 200 OK in 5ms (Views: 3.0ms | ActiveRecord: 0.9ms)
2017-01-12T15:56:15.620643+00:00 heroku[router]: at=info method=GET path="/datasets/created" host=fsa-octopub.herokuapp.com request_id=e356437f-88de-42b6-a34d-850a8990c0c1 fwd="85.115.54.201" dyno=web.1 connect=0ms service=9ms status=200 bytes=3051
2017-01-12T15:56:28.334805+00:00 app[worker.1]: 4 TID-ovdtne87g WARN: {"class":"CreateDataset","args":[{"name":"Approved Food Establishments","owner":"fsadata","description":"A full list of establishments approved to handle, prepare or produce products of animal origin for which requirements are laid down in Regulation (EC) No 853/2004.","publisher_name":"Food Standards Agency","publisher_url":"https://www.food.gov.uk","license":"OGL-UK-3.0","frequency":"Monthly","schema":"https://fsa-octopub.s3-eu-west-1.amazonaws.com/uploads/<redacted>/ApprovedFoodEstablishments.json"},[{"title":"Approved Food Establishments","description":"A full list of establishments approved to handle, prepare or produce products of animal origin for which requirements are laid down in Regulation (EC) No 853/2004.","file":"https://fsa-octopub.s3-eu-west-1.amazonaws.com/uploads/<redacted>/ApprovedFoodEstablishments.csv"}],6,{"channel_id":"post-30e5e8d2-e586-4ffc-a317-337f9fa9ecd7"}],"retry":false,"queue":"default","jid":"b17ae9ac5570d685bcbfadaa","created_at":1484236567.8226683,"enqueued_at":1484236567.8227603}
2017-01-12T15:56:28.334842+00:00 app[worker.1]: 4 TID-ovdtne87g WARN: Octokit::Conflict: POST https://api.github.com/repos/fsadata/approved-food-establishments/git/refs: 409 - Git Repository is empty. // See: https://developer.github.com/v3/git/refs/#create-a-reference
2017-01-12T15:56:28.334682+00:00 app[worker.1]: 4 TID-ovdtne87g CreateDataset JID-b17ae9ac5570d685bcbfadaa INFO: fail: 20.518 sec
2017-01-12T15:56:28.334901+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
2017-01-12T15:56:28.334899+00:00 app[worker.1]: 4 TID-ovdtne87g WARN: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
2017-01-12T15:56:28.334901+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
2017-01-12T15:56:28.334902+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
2017-01-12T15:56:28.334903+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
2017-01-12T15:56:28.334904+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
2017-01-12T15:56:28.334908+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
2017-01-12T15:56:28.334905+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
2017-01-12T15:56:28.334906+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
2017-01-12T15:56:28.334910+00:00 app[worker.1]: /app/lib/git_data.rb:17:in `create'
2017-01-12T15:56:28.334906+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
2017-01-12T15:56:28.334907+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
2017-01-12T15:56:28.334908+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/connection.rb:28:in `post'
2017-01-12T15:56:28.334909+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.3.0/lib/octokit/client/refs.rb:54:in `create_ref'
2017-01-12T15:56:28.334911+00:00 app[worker.1]: /app/app/models/dataset.rb:170:in `create_in_github'
2017-01-12T15:56:28.334913+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
2017-01-12T15:56:28.334911+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:429:in `block in make_lambda'
2017-01-12T15:56:28.334914+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:503:in `block in call'
2017-01-12T15:56:28.334915+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:503:in `call'
2017-01-12T15:56:28.334912+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:224:in `call'
2017-01-12T15:56:28.334913+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:503:in `call'
2017-01-12T15:56:28.334916+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:86:in `run_callbacks'
2017-01-12T15:56:28.334915+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:503:in `each'
2017-01-12T15:56:28.334918+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/persistence.rb:484:in `create_or_update'
2017-01-12T15:56:28.334917+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/callbacks.rb:306:in `_create_record'
2017-01-12T15:56:28.334920+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:113:in `call'
2017-01-12T15:56:28.334918+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/timestamp.rb:57:in `_create_record'
2017-01-12T15:56:28.334921+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
2017-01-12T15:56:28.334919+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/callbacks.rb:302:in `block in create_or_update'
2017-01-12T15:56:28.334921+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:113:in `call'
2017-01-12T15:56:28.334924+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/callbacks.rb:302:in `create_or_update'
2017-01-12T15:56:28.334939+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/validations.rb:51:in `save'
2017-01-12T15:56:28.334922+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:502:in `call'
2017-01-12T15:56:28.334923+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:502:in `call'
2017-01-12T15:56:28.334940+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
2017-01-12T15:56:28.334923+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.16/lib/active_support/callbacks.rb:86:in `run_callbacks'
2017-01-12T15:56:28.334941+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
2017-01-12T15:56:28.334938+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/persistence.rb:103:in `save'
2017-01-12T15:56:28.334946+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
2017-01-12T15:56:28.334939+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/attribute_methods/dirty.rb:21:in `save'
2017-01-12T15:56:28.334946+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
2017-01-12T15:56:28.334951+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
2017-01-12T15:56:28.334950+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:268:in `block in save'
2017-01-12T15:56:28.334947+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
2017-01-12T15:56:28.334955+00:00 app[worker.1]: /app/app/models/dataset.rb:23:in `report_status'
2017-01-12T15:56:28.334948+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:208:in `transaction'
2017-01-12T15:56:28.334956+00:00 app[worker.1]: /app/app/jobs/create_dataset.rb:19:in `perform'
2017-01-12T15:56:28.334957+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
2017-01-12T15:56:28.334949+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
2017-01-12T15:56:28.334955+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/transactions.rb:267:in `save'
2017-01-12T15:56:28.334958+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2017-01-12T15:56:28.334959+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2017-01-12T15:56:28.334957+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
2017-01-12T15:56:28.334959+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-12T15:56:28.334960+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2017-01-12T15:56:28.334960+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-12T15:56:28.334961+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2017-01-12T15:56:28.334962+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'
2017-01-12T15:56:28.334962+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2017-01-12T15:56:28.334963+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-12T15:56:28.334964+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2017-01-12T15:56:28.334965+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'
2017-01-12T15:56:28.334966+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'
2017-01-12T15:56:28.334966+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'
2017-01-12T15:56:28.334964+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `call'
2017-01-12T15:56:28.334967+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'
2017-01-12T15:56:28.334968+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
2017-01-12T15:56:28.334968+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
2017-01-12T15:56:28.334969+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by Floppy** [comment]
Upload failed because of a 409 response, github repository empty.

**Comment by Floppy** [comment]
Error occurred on git_data.rb#17: 

```
client.create_ref(full_name, 'heads/gh-pages', branch_data.commit.sha)
```

**Comment by Floppy** [comment]
From https://developer.github.com/v3/git/:

```
Git DB API functions will return a 409 Conflict if the git repository for a Repository is empty or unavailable. This typically means it is being created still. Contact Support if this response status persists.
```

**Comment by Floppy** [comment]
So I reckon that means that the repository wasn't done being created in the create_repository call on line 8 (or 10). That call must be asynchronous, which means we should check the repository exists before continuing to work with it.

**Comment by jamesjefferies** [comment]
This has been highlighted as an issue with large files
