### ISSUE TITLE
Uploading dataset with schema spins forever on octopub.io

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#554]
Not happening on the FSA instance. All workers are running.

**Comment by Floppy** [comment]
Happening on all instances now.

**Comment by quadrophobiac** [comment]
+1 for consistency

**Comment by Floppy** [comment]
Replicated locally as well.

**Comment by Floppy** [comment]
```
Errno::ENOENT - No such file or directory @ rb_sysopen - uploads/5d366622-6ca3-434e-9f36-dbecdc5e54f3/CorrespondenceCaseRecord_Branch_20170804.json:
  /Users/james/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
  app/services/dataset_file_schema_service.rb:53:in `read_file_with_utf_8'
  app/services/dataset_file_schema_service.rb:45:in `load_json_from_s3'
  app/services/dataset_file_schema_service.rb:31:in `update_dataset_file_schema_with_json_schema'
  app/services/dataset_file_schema_service.rb:19:in `create_dataset_file_schema'
```

**Comment by Floppy** [comment]
Looks like the schema file is using the same storage key as the CSV file:

`DatasetFile: In file_from_url_with_storage_key - 'uploads/5d366622-6ca3-434e-9f36-dbecdc5e54f3/2016CorrespondenceCaseRecord_Branch20170804.csv'`

This is *probably* wrong.

**Comment by Floppy** [comment]
working now on octopub after #603 was merged to revert previous breaking change.

**Comment by Floppy** [comment]
verified on fsa-octopub as well.
