### ISSUE TITLE
Applying a schema to existing dataset files spins forever

### ISSUE THREAD

**Issue by Floppy** [theodi/octopub#633]
See https://fsa-octopub.herokuapp.com/datasets/127/edit - if you add schemas, and save, nothing happens.

**Comment by Floppy** [comment]
Verified on https://octopub.io/datasets/342/edit editing the first dataset file, changing schema.

**Comment by Floppy** [comment]
Seems to be an explosion when trying to read and parse the CSV file from S3, which may well not be there any more. I'm a bit worried we're expecting S3 to be persistent storage, but also not making sure it is.

**Comment by Floppy** [comment]
```
2017-10-06T14:28:03.939411+00:00 app[worker.1]: 4 TID-osnf9o6pg WARN: Aws::S3::Errors::NoSuchKey: The specified key does not exist.

... 

2017-10-06T14:28:03.939502+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.4.0/lib/aws-sdk-s3/object.rb:657:in `get'
2017-10-06T14:28:03.939503+00:00 app[worker.1]: /app/app/services/file_storage_service.rb:21:in `get_string_io'
2017-10-06T14:28:03.939504+00:00 app[worker.1]: /app/app/models/dataset_file.rb:157:in `validate_schema_non_cotw'
2017-10-06T14:28:03.939504+00:00 app[worker.1]: /app/app/models/dataset_file.rb:127:in `check_schema'
```

**Comment by Floppy** [comment]
The file does have a `storage_key`... so it's not that.

**Comment by Floppy** [comment]
calling `#check_schema` on the file produces the same result.

**Comment by Floppy** [comment]
So we have a file that is published, but is no longer in S3, so we can't verify it against a new (or even the same) schema. Seems to me that the right thing to do would be to use the publicly-published file first, then fall back to S3 if it's not available (i.e. is private somehow).
